name: 'Markdown Code Embed'
description: Embeds code into README with MDCE
branding:
  color: purple
  icon: file-text

inputs:
  args:
    description: |
      Embed code within markdown documents

      options:
        -h, --help            show this help message and exit
        -d directory [directory ...], --directories directory [directory ...]
                              Directories to be scanned for README.md files
        -f file_name [file_name ...], --files file_name [file_name ...]
                              Files to be scanned
        -e directory [directory ...], --exclude directory [directory ...]
                              Directories to exclude from searching
        -i, --include-self    Includes the directory (and sub-directories with -s)
                              of this script when parsing
        -s, --sub             Checks all sub-directories
        -b, --backup          Backs up the original file, appending ".old" to the
                              file name
        -g, --ignore-git      Exit value ignores changes in git
        -u, --ignore-untracked
                              Exit value ignores changes to untracked files
        -q, --quiet           Reduces the number of messages printed
    required: false
    default: ""
  version:
    description: The version of MDCE to be used
    required: false
    default: "2.0.0"

runs:
  using: "composite"
  steps:
    - name: Clone MDCE and get version
      shell: bash
      run: |
        git clone https://github.com/ippie52/markdown_code_embed.git && 
        cd markdown_code_embed && 
        git checkout ${{ inputs.version }}
    - name: Run MDCE
      shell: bash
      run:  ./markdown_code_embed/mdce.py ${{ inputs.args }}
