name: 'Markdown Code Embed'
description: Embeds code into README with MDCE
branding:
  color: purple
  icon: file-text

inputs:
  args:
    description: |
      Embed code within markdown documents

      options:
        -h, --help            show this help message and exit
        -d directory [directory ...], --directories directory [directory ...]
                              Directories to be scanned for README.md files
        -f file name [file name ...], --files file name [file name ...]
                              Files to be scanned
        -s, --sub             Checks all sub-directories
        -b, --backup          Backs up the original file, appending ".old" to the
                              file name
        -g, --ignore-git      Exit value ignores changes in git
        -u, --ignore-untracked
                              Exit value ignores changes to untracked files
        -q, --quiet           Reduces the number of messages printed
    required: false
    default: "-h"

runs:
  using: "composite"
  steps:
    - name: Run MDCE
      shell: bash
      run:  ${{ github.action_path }}/mdce.py ${{ inputs.args }}
